### ISSUE TITLE
[python-pytorch-rocm] Compiling and running PyTorch with ROCm on Archlinux

### ISSUE THREAD

**Issue by s-bernard** [rocm-arch/python-pytorch-rocm#1]
Hi everyone,

First, thanks a lot for maintaining the ROCm packages, it's not easy and you're doing a great job.

A week ago, I decided to try PyTorch with ROCm on my Arch so I began the compilation process. Then it failed, I found a way to remove the error, then it failed again, I fixed it, then again, etc.
I finally succeeded to have a working* version so I've compiled all the patches I did to share them with you.

PR rocm-arch/rocm-arch#134 : PyTorch depends on most of the ROCm stack, so I needed to update everything to 3.3.0

PR rocm-arch/rocm-arch#132 : one library way more complicated to upgrade was MIOpen. The raison is it needs rocblas with tensile. But compiling rocblas with tensile was quite a journey.

PR rocm-arch/rocm-arch#133 : PyTorch build failed a few times because some include files were not found. By looking at ubuntu docker, I found that most of them were symlinks in `/opt/rocm/include`.

PR: rocm-arch/rocm-arch#131 : The most tricky error was at runtime, with an LLVM error `:CommandLine Error: Option 'disable-symbolication' registered more than once!`. After some digging, comparing with ubuntu docker which was working fine, I found that my version of PyTorch was linked to a ROCm LLVM library, Ubuntu was not.
So I looked at llvm-roc and found that it builds and links DYLIB, which was the shared library linked to PyTorch. I compiled LLVM without it, same for Comgr and the problem was solved. Bonus, llvm-roc (or llvm-amdgpu) is not needed after Comgr is built.

Finally, there is still an issue for which I do not have a PR yet. Due to capitalization mixup in project names (hip/HIP, hcc/HCC, …), in the cmake files, some project cannot be found when you launch cmake on PyTorch. With some patches on PyTorch, I improved the situation but at the end, I still needed to edit the cmake files of subproject (like `/opt/rocm/rccl/lib/cmake/rccl/rccl-config.cmake`) to change `find_dependency(hip)` by `find_dependency(HIP)`

Thanks.

*I still have issues on some *cuda* tests, I'll find a way ;)

**Comment by acxz** [comment]
Reopening this issue since the original issue is still a problem we would like to tackle as the Arch community

**Comment by acxz** [comment]
> i edit PKGBUILD export USE_ROCM=ON before compilation

@chiboreache looking closer at the CMakeLists.txt I think the flag should be `USE_ROCM=1`. Can you try again with the current PKGBUILD in this repo and report any bugs you face?

**Comment by acxz** [comment]
I'll go ahead and close this. Disc has been staled.

**Comment by chiboreache** [comment]
_was too busy, sorry_

it seems maintainer updated the pkgbuild, but it doesn't helped

<img width="539" alt="Screenshot_20200723_064119" src="https://user-images.githubusercontent.com/16459251/88251310-29293480-ccb3-11ea-8315-3f9f53cd076a.png">


```sh
***** Library versions from cmake find_package *****

CMake Error at cmake/public/LoadHIP.cmake:131 (find_package):
By not providing "Findrocrand.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "rocrand", but
CMake did not find one.

Could not find a package configuration file provided by "rocrand" with any
of the following names:

rocrandConfig.cmake
rocrand-config.cmake

Add the installation prefix of "rocrand" to CMAKE_PREFIX_PATH or set
"rocrand_DIR" to a directory containing one of the above files.  If
"rocrand" provides a separate development package or SDK, be sure it has
been installed.
Call Stack (most recent call first):
cmake/public/LoadHIP.cmake:167 (find_package_and_print_version)
cmake/Dependencies.cmake:995 (include)
CMakeLists.txt:411 (include)


-- Configuring incomplete, errors occurred!
See also "/home/chibo/.cache/pikaur/build/python-pytorch-rocm/src/pytorch-1.5.1-rocm/build/CMakeFiles/CMakeOutput.log".
See also "/home/chibo/.cache/pikaur/build/python-pytorch-rocm/src/pytorch-1.5.1-rocm/build/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
File "setup.py", line 744, in <module>
build_deps()
File "setup.py", line 311, in build_deps
build_caffe2(version=version,
File "/home/chibo/.cache/pikaur/build/python-pytorch-rocm/src/pytorch-1.5.1-rocm/tools/build_pytorch_libs.py", line 54, in build_caffe2
cmake.generate(version,
File "/home/chibo/.cache/pikaur/build/python-pytorch-rocm/src/pytorch-1.5.1-rocm/tools/setup_helpers/cmake.py", line 323, in generate
self.run(args, env=my_env)
File "/home/chibo/.cache/pikaur/build/python-pytorch-rocm/src/pytorch-1.5.1-rocm/tools/setup_helpers/cmake.py", line 141, in run
check_call(command, cwd=self.build_dir, env=env)
File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-DBUILD_BINARY=ON', '-DBUILD_PYTHON=True', '-DBUILD_TEST=True', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_INSTALL_PREFIX=/home/chibo/.cache/pikaur/build/python-pytorch-rocm/src/pytorch-1.5.1-rocm/torch', '-DCMAKE_PREFIX_PATH=/usr/lib/python3.8/site-packages', '-DCUDNN_INCLUDE_DIR=/usr/include', '-DCUDNN_LIBRARY=/usr/lib', '-DNUMPY_INCLUDE_DIR=/usr/lib/python3.8/site-packages/numpy/core/include', '-DPYTHON_EXECUTABLE=/usr/bin/python', '-DPYTHON_INCLUDE_DIR=/usr/include/python3.8', '-DPYTHON_LIBRARY=/usr/lib/libpython3.8.so.1.0', '-DTORCH_BUILD_VERSION=1.5.1', '-DUSE_FFMPEG=ON', '-DUSE_GFLAGS=ON', '-DUSE_GLOG=ON', '-DUSE_MKLDNN=ON', '-DUSE_NUMPY=True', '-DUSE_OPENCV=ON', '-DUSE_ROCM=1', '-DUSE_SYSTEM_NCCL=ON', '/home/chibo/.cache/pikaur/build/python-pytorch-rocm/src/pytorch-1.5.1-rocm']' returned non-zero exit status 1.
==> ERROR: A failure occurred in build().
Aborting...
```
