### ISSUE TITLE
Don't pull in 6GB of magma+cuda and the nvidia stuff

### ISSUE THREAD

**Issue by erratic-c-programmer** [rocm-arch/python-pytorch-rocm#10]
It's a waste of space, and pytorch doesn't seem to need it, and we don't if we're building for ROCm... right?

**Comment by acxz** [comment]
Yeah we def don't need to have cuda as a dep, as for magma we need to change that to `hipmagma` however that package still does not exist in the AUR. Once we can switch magma to hipmagma we should be fine to remove the cuda dep.

**Comment by acxz** [comment]
Looking a bit closer into to this it seems that hipmagma is not integrated with pytorch yet. https://github.com/pytorch/pytorch/issues/48831

As such yeah le't remove magma dep for now.

**Comment by acxz** [comment]
Resolved with d3a578b
