### ISSUE TITLE
Invalid token in preprocessing 

### ISSUE THREAD

**Issue by nquest** [rocm-arch/python-pytorch-rocm#12]
Trying to build pytorch and got this: 
Trying to investigate, maybe compiler selection problem

    FAILED: caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_pow_op.hip.o 
    cd /home/nquest/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/caffe2/CMakeFiles/torch_hip.dir/operators/hip && /usr/bin/cmake -E make_directory /home/nquest/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/caffe2/CMakeFiles/torch_hip.dir/operators/hip/. && /usr/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=RELEASE -D generated_file:STRING=/home/nquest/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/caffe2/CMakeFiles/torch_hip.dir/operators/hip/./torch_hip_generated_pow_op.hip.o -P /home/nquest/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/caffe2/CMakeFiles/torch_hip.dir/operators/hip/torch_hip_generated_pow_op.hip.o.cmake
    In file included from /home/nquest/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/caffe2/operators/hip/pow_op.hip:8:
    In file included from /home/nquest/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/caffe2/operators/pow_op.h:8:
    In file included from /home/nquest/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/caffe2/operators/elementwise_ops.h:15:
    In file included from /home/nquest/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/caffe2/utils/eigen_utils.h:6:
    In file included from /home/nquest/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/cmake/../third_party/eigen/Eigen/Core:22:
    /home/nquest/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/cmake/../third_party/eigen/Eigen/src/Core/util/ConfigureVectorization.h:404:26: error: invalid token at start of a preprocessor expression
      #if (HIP_VERSION_PATCH < HIP_PATCH_WITH_NEW_FP16)
                             ^
    1 error generated when compiling for gfx803.
    CMake Error at torch_hip_generated_pow_op.hip.o.cmake:192 (message):
      Error generating file
      /home/nquest/.cache/yay/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/caffe2/CMakeFiles/torch_hip.dir/operators/hip/./torch_hip_generated_pow_op.hip.

**Comment by nquest** [comment]
`/opt/rocm/hip/bin/hipconfig -vn` produces `4.0.`, so HIP_VERION_PATCH maybe not defined. Truing to fix this.

**Comment by nquest** [comment]
So, HIP_VERSION_PATCH fixed.
Now it's another problem with protobuf:
`/usr/bin/ld: /home/nquest/src/arch-repos/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/lib/libtorch_hip.so: undefined reference to caffe2::DeviceOption::DeviceOption(google::protobuf::Arena*)
/usr/bin/ld: /home/nquest/src/arch-repos/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/lib/libtorch_hip.so: undefined reference to caffe2::OperatorDef::OperatorDef(google::protobuf::Arena*)
/usr/bin/ld: /home/nquest/src/arch-repos/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/lib/libtorch_hip.so: undefined reference to caffe2::NetDef::NetDef(google::protobuf::Arena*)'
/usr/bin/ld: /home/nquest/src/arch-repos/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/lib/libtorch_hip.so: undefined reference to caffe2::TensorShape::TensorShape(google::protobuf::Arena*)
`

**Comment by nquest** [comment]
OK, finally it compiles!
But need to use BUILD_CUSTOM_PROTOBUF=ON, because official ROCm docker images installs protobuf 2.6.1 in [this](https://github.com/pytorch/pytorch/blob/21398fb6cbc7371814c2c64fb463c0c7c7639c18/.circleci/docker/common/install_protobuf.sh#L5) build script and we have 3.12.4

**Comment by acxz** [comment]
Can  you post the build error for the protobuf related issue as a separate issue? Thanks!

**Comment by acxz** [comment]
Upstream issue: https://github.com/pytorch/pytorch/issues/49768

**Comment by acxz** [comment]
hmm the hip_version_patch could be due to a packaging inconsistency over at https://github.com/rocm-arch/rocm-arch

**Comment by nquest** [comment]
> Can you post the build error for the protobuf related issue as a separate issue? Thanks!

#14

**Comment by acxz** [comment]
I believe this issue is resolved with the resolution of the above issue. 
c4275f3

**Comment by nquest** [comment]
Not sure if it's worth commenting on a closed  issue. Now rebuilding without patch.
