### ISSUE TITLE
Linking error with system-wide protobuf

### ISSUE THREAD

**Issue by nquest** [rocm-arch/python-pytorch-rocm#14]
There is an linking error with current arch's protobuf 3.12.4:

`/usr/bin/ld: /home/nquest/src/arch-repos/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/lib/libtorch_hip.so: undefined reference to caffe2::DeviceOption::DeviceOption(google::protobuf::Arena*)
/usr/bin/ld: /home/nquest/src/arch-repos/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/lib/libtorch_hip.so: undefined reference to caffe2::OperatorDef::OperatorDef(google::protobuf::Arena*)
/usr/bin/ld: /home/nquest/src/arch-repos/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/lib/libtorch_hip.so: undefined reference to caffe2::NetDef::NetDef(google::protobuf::Arena*)'
/usr/bin/ld: /home/nquest/src/arch-repos/python-pytorch-rocm/src/pytorch-1.7.1-rocm/build/lib/libtorch_hip.so: undefined reference to caffe2::TensorShape::TensorShape(google::protobuf::Arena*)
`
So need to set BUILD_CUSTOM_PROTOBUF=ON because official ROCm docker images installs protobuf 2.6.1 in this build script and we have 3.12.4
Workaround in #13

**Comment by acxz** [comment]
hmm I wonder what the proper fix for this is?
Could this be an issue with the pytorch source code?

**Comment by acxz** [comment]
@nquest can you make an upstream issue at pytorch/pytorch and link it back here?
It won't get fixed if upstream doesn't know about it ;)

**Comment by nquest** [comment]
Upstream: https://github.com/pytorch/pytorch/issues/50001

**Comment by acxz** [comment]
I'm removing the patched label as I have set `export BUILD_CUSTOM_PROTOBUF=OFF` back to OFF. This is because the Archlinux package does the same. Once I fix the new rocm dep issue, I'll come back to investigate this issue and decide if we need this patch or not with the newer pytorch version.

**Comment by acxz** [comment]
This issue is not appearing in the later pytorch releases. Feel free to comment here if you are still experiencing this.
