### ISSUE TITLE
gfx902 binnaries

### ISSUE THREAD

**Issue by Sotwi-zz** [rocm-arch/python-pytorch-rocm#26]
This may be a dumb question.
I installed this package but when I try to move a model to the gpu I get the following error:

`/build/hip-rocclr/src/HIP-rocm-4.0.0/rocclr/hip_code_object.cpp:120: guarantee(false && "hipErrorNoBinaryForGpu: Coudn't find binary for current devices!")`

The GPU is a AMD Ryzen 3 PRO 2300U w (gfx902) which I know is not officially supported by ROCm, however, I was wondering if there's a workaround or if I should just give up with making PyTorch work on this machine.

I'll attach the output of rocminfo and clinfo in case it's useful.
[rocminfo.txt](https://github.com/rocm-arch/python-pytorch-rocm/files/6085719/rocminfo.txt)
[clinfo.txt](https://github.com/rocm-arch/python-pytorch-rocm/files/6085720/clinfo.txt)

Thank you in advance!

**Comment by alex4o** [comment]
there is no way to make this work with an integrated gpu :(

**Comment by acxz** [comment]
Closing this issue as we can't really control the compatibility of amd devices with rocm. I suggest posting this issue to the ROCM repos directly.
