### ISSUE TITLE
`/opt/rocm/.info/version-dev` not found

### ISSUE THREAD

**Issue by acxz** [rocm-arch/python-pytorch-rocm#32]
Error:
```
HIP VERSION: 5.0.13601-026cbab
CMake Error at cmake/public/LoadHIP.cmake:154 (file):
  file failed to open for reading (No such file or directory):

    /opt/rocm/.info/version-dev
Call Stack (most recent call first):
  aten/CMakeLists.txt:61 (include)
```

Upstream PR: https://github.com/pytorch/pytorch/pull/69481

**Comment by acxz** [comment]
patched with https://github.com/rocm-arch/python-pytorch-rocm/blob/3c0bae28dc5b9fbd96a3a0c00eada71b90fda6fa/PKGBUILD#L193-L194

**Comment by acxz** [comment]
new rc has patch, closing

**Comment by JP-Ellis** [comment]
Should this be fixed by patching `pytorch`, or should `rocm-core` provide this file?

**Comment by acxz** [comment]
`rocm-core` used to provide this file, but in later versions it does not. A newer release of `pytorch` will have the associated fix. Notice that I am pulling the patch directly from the `pytorch` repo.
