### ISSUE TITLE
Build for unofficial supported GPU

### ISSUE THREAD

**Issue by ZappaBoy** [rocm-arch/python-pytorch-rocm#43]
Hi all,
Is there a clear guide on how to build pytorch with rocm support for an unofficial GPU?
I need to build pytorch for the AMD Radeon 6700XT, I found someone who made it work, but there isn't a clean guide: [thread link](https://www.reddit.com/r/Amd/comments/rd7mmi/heres_something_you_dont_see_every_day_pytorch/);

The only set of command that I found in the comments is ([comment link](https://www.reddit.com/r/Amd/comments/rd7mmi/comment/ho0xpxf/?utm_source=share&utm_medium=web2x&context=3)):

> For anyone interested in getting [this](https://github.com/micmelesse/pytorch) to run, here are the steps I needed to follow for a 6900XT:
> 
> Clone this pytorch fork (`git clone --recursive https://github.com/micmelesse/pytorch`)
> 
> git checkout to the `fix_warpsize_issue` branch
> 
> Run `python3 tools/amd_build/build_amd.py`
> 
> Run `python3 setup.py build --cmake-only` and then `ccmake build`. In the TUI for ccmake build, change `AMDGPU_TARGETS` and `GPU_TARGETS` to `gfx1030`. Press configure and then generate.
> 
> Run `PYTORCH_ROCM_ARCH=gfx1030 python3 setup.py install`. Takes a LONG time even on a 5900X.

Obviously i followed that instruction with the parameter `gfx1031`, also tried to recompile all `rocm` packages in [rocm-arch/rocm-arch](https://github.com/rocm-arch/rocm-arch) repository with `gfx1031` but none works. 

Does anyone know how to build this also if 6700XT is not officially supported?

**Comment by acxz** [comment]
Would build error are you getting if you just try to build the PKGBUILD as is? If you post that, maybe we can take a look at it and figure out how to fix the error.

**Comment by JP-Ellis** [comment]
I will just add one thing: if the upstream developers at ROCm don't intent to officially support a platform, then there's no guarantee that "forcing" the compilation will allow things to work. Having said that, if you've identified a particular issue and found the fix for it, they are generally receptive to PRs.
