### ISSUE TITLE
build of python-torchtext 0.13.0-1 breaks on current pytorch-rocm using rocm 5.2.x

### ISSUE THREAD

**Issue by wuxxin** [rocm-arch/python-pytorch-rocm#46]
+ aur package: https://aur.archlinux.org/packages/python-torchtext

+ build breaks on pytorch related files:

```
CMake Error at /usr/lib64/cmake/Caffe2/Caffe2Targets.cmake:102 (set_target_properties):
  The link interface of target "torch_hip_library" contains:

    roc::rocblas

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /usr/lib64/cmake/Caffe2/Caffe2Config.cmake:116 (include)
  /usr/lib64/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:54 (find_package)
```

**Comment by acxz** [comment]
How can I recreate the error?

**Comment by wuxxin** [comment]
sry for the missing information,
reproduction: build using a aur helper, eg. pikaur:
```
pikaur -S python-torchtext
```

**Comment by acxz** [comment]
This might be an upstream issue as this might be the first time anyone has compiled `python-torchtext` with rocm. Can you make an upstream issue and link it back here.

**Comment by wuxxin** [comment]
ack, will do

**Comment by acxz** [comment]
by upstream here, im referring to the upstream of python-torchtext btw. But maybe pytorch is not exporting the rocblas target.

**Comment by acxz** [comment]
Thanks for digging into this and I'm glad there exists a solution. I'll move this over to discussions as it doesn't pertain to pytorch in a direct manner.

**Comment by wuxxin** [comment]
i wanted to recompile with 0.13.1 but currently pytorch 1.12.0 Rev 7 breaks building python-pytorch-rocm, see https://github.com/rocm-arch/python-pytorch-rocm/issues/47

**Comment by wuxxin** [comment]
i can report success building torchtext 0.13.1 from updated AUR source for the ROCM version of pytorch

**Comment by wuxxin** [comment]
works for me, closing, please revert if not fitting
